### ISSUE TITLE
missing data and function

### ISSUE THREAD

**Issue by osaaso3** [dimarkov/aibandits#1]
Hi Dimitrije,
Great notebooks, but please add missing data (e.g., switching...) and functions (e.g., confusions in swtch, swtch1, swtch2, but drift works), as some notebooks are not working well.

**Comment by dimarkov** [comment]
Hi, thanks for testing the notebooks. You can download the data folder from the [project page](https://osf.io/85ek4/) on OSF. I forgot to include that in the readme file. I will update it soon. 

Which notebooks specifically you have problems with?

**Comment by dimarkov** [comment]
I have updated the README.md file with information where to get the missing files for recreating the figures without having to run the simulations. 

As far as the problem with function goes I am not able to recreate that. All the notebooks work for me. If the problem still persists please open another issue with more details.

**Comment by osaaso3** [comment]
Thanks for the data file, I'll check it out. 
The other problem is in inference_algorithms_comparison.ipynb.
It uses environment.py where some sw[i?]tch functions are defined. The process variable in the notebook call generative_process_swtch but only ...swtch1 and ...swtch2 and drift exist...and it fails when I change it to swtch1 or swtch2

error using ..swtch1:
UnfilteredStackTrace                      Traceback (most recent call last)
<ipython-input-21-00f15daf90fc> in <module>()
      1 N = 1
----> 2 sequence = simulator(process, N=N)
      3 

20 frames
UnfilteredStackTrace: KeyError: 'N'

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
/content/drive/My Drive/Colab Notebooks/Prg/Markovic/Bandits/environment.py in generative_process_swtch1(t, choices, states, rng_key, logits, **kwargs)
     15     changes to another arm with probability \rho or remains on the same arm with probability 1 - \rho.
     16     """
---> 17     N = kwargs['N']
     18     K = kwargs['K']
     19     eps = kwargs['eps']

KeyError: 'N'
