### ISSUE TITLE
swtch function error in inference_algorithms_comparison.ipynb-environment.py

### ISSUE THREAD

**Issue by osaaso3** [dimarkov/aibandits#2]
Thanks for the data, I'll check it out.
The other problem is in inference_algorithms_comparison.ipynb.
It uses environment.py where some sw[i?]tch functions are defined. The process variable in the notebook call generative_process_swtch but only ...swtch1 and ...swtch2 and drift exist...and it fails when I change it to swtch1 or swtch2

error using ..swtch1:
UnfilteredStackTrace Traceback (most recent call last)
in ()
1 N = 1
----> 2 sequence = simulator(process, N=N)
3

20 frames
UnfilteredStackTrace: KeyError: 'N'

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

The above exception was the direct cause of the following exception:

KeyError Traceback (most recent call last)
/content/drive/My Drive/Colab Notebooks/Prg/Markovic/Bandits/environment.py in generative_process_swtch1(t, choices, states, rng_key, logits, **kwargs)
15 changes to another arm with probability \rho or remains on the same arm with probability 1 - \rho.
16 """
---> 17 N = kwargs['N']
18 K = kwargs['K']
19 eps = kwargs['eps']

KeyError: 'N'

**Comment by dimarkov** [comment]
Great, I can fix this tomorrow. This notebook was not holding the content for the paper so I did not test it after introducing some changes in generative process methods.

**Comment by osaaso3** [comment]
Thanks!

**Comment by dimarkov** [comment]
So I have fixed the notebook, it should run now through all the inference examples. Note that I have been using here only generative_process_swtch2 and generative_process_drift methods from environment.py. 

Eventually I will implement all the different inference algorithm inside learning_algos.py for comparison in Bayesian bandits. Maybe in the next couple of weeks when I find some free time. For now this was just an exploratory notebook to see if there is any large difference in posterior estimates between different variants.

**Comment by osaaso3** [comment]
Thanks, good job. I'll try it soon.
